### ISSUE TITLE
Preview stretch

### ISSUE THREAD

**Issue by Chesteer89** [journeyapps/zxing-android-embedded#33] opened 2015-04-09 10:44 UTC
Hi,

Preview size is stretching when camera and preview orientation are different. It should be fixed :) For example:
I/DisplayConfiguration﹕ Preview: 600x800; Scaled: 1800x2400; Want: 1280x752

**Comment by rkistner** [comment] 2015-04-09 11:01
I assume this is the 3.x branch? Which devices is this? By stretched, do you mean zoomed, but still correct aspect ratio, or is the aspect ratio distorted?

Can you please give me the list of preview sizes for the device? Should be logged in `Preview in order of preference: ...`.

Scaling up is intended behaviour, but this is probably more than it should be. It is quite possibly also an issue with the orientation as you mentioned - will look into it.

**Comment by Chesteer89** [comment] 2015-04-09 11:16
Preview in order of preference: [800x600, 320x240]

Yes, it's 3.x branch. I'm working right now on Samsung GT-P7500, i'll check it on Nexus 7 later. 
By stretched i mean that ratio is distorted, as you can see:

Preview: 600x800; Scaled: 1800x2400; Want: 1280x752

So imho in landscape it should be:
Preview: 600x800; Scaled: 1800x2400; Want: 752x1280

Ofc i made fast fix:
```
if((scaledPreview.width > scaledPreview.height && viewfinderSize.width < viewfinderSize.height) ||
   scaledPreview.width < scaledPreview.height && viewfinderSize.width > viewfinderSize.height){
   dx = (scaledPreview.height - viewfinderSize.width) / 2;
   dy = (scaledPreview.width - viewfinderSize.height) / 2;

   return new Rect(-dx, -dy, scaledPreview.height - dx, scaledPreview.width - dy);
   }

dx = (scaledPreview.width - viewfinderSize.width) / 2;
dy = (scaledPreview.height - viewfinderSize.height) / 2;
return new Rect(-dx, -dy, scaledPreview.width - dx, scaledPreview.height - dy);
```

**Comment by rkistner** [comment] 2015-04-09 11:42
I'm guessing that the issue is in the `isRotated()` function in DisplayConfiguration. Since this is a tablet, I'm guessing the "natural" orientation is landscape, which may not be handled correctly. Does it work if instead of your fix, you switch around the result of `isRotated()`?

**Comment by Chesteer89** [comment] 2015-04-09 11:48
Yes, when i changed result in isRotated it works :)

**Comment by rkistner** [comment] 2015-04-09 11:49
Thanks, that's good to know. Then I just need to figure out how to detect the natural orientation, so that `isRotated()` can work correctly on all devices.

**Comment by Chesteer89** [comment] 2015-04-09 12:02
You can check it here:
http://stackoverflow.com/questions/4553650/how-to-check-device-natural-default-orientation-on-android-i-e-get-landscape

Anyway, thanks for fast reply. Good work!

**Comment by rkistner** [comment] 2015-04-09 14:36
Will you please test with the latest version? Should be fixed in the 2d09eca09431 commit.

It now uses the same logic as for `Camera#setDisplayOrientation()` to determine whether or the preview is rotated against the display, which removes the need to determine the device's natural display orientation (only the relative orientation matters).

**Comment by Chesteer89** [comment] 2015-04-09 17:01
I'll test it tomorrow morning and I'll let you know

**Comment by rkistner** [comment] 2015-04-09 19:02
Added another fix in #522414fa30cb1662f (rotation of the image for decoding). Please also check that the ResultPoints (yellow dots) match up with the barcode.

**Comment by Chesteer89** [comment] 2015-04-10 06:03
It's working well right now :+1:

**Comment by rkistner** [comment] 2015-04-10 06:41
Great, thanks for the report and testing.

**Closed by rkistner** 2015-04-10 06:41 UTC

**Comment by zavernutiy** [comment] 2015-04-10 09:55
Hi. I have a similar problem but on my Sony Xperia Z1 Compact. I changed the orientation to vertical and aspect ratio went wrong. It strethes the picture 
![screenshot_2015-04-10-12-41-48](https://cloud.githubusercontent.com/assets/2391710/7085507/f4927ebe-df7f-11e4-9559-34b52c6c3e8f.png)
![screenshot_2015-04-10-12-42-04](https://cloud.githubusercontent.com/assets/2391710/7085506/f4913306-df7f-11e4-8970-a893043cf59b.png)
Here is the code:
        IntentIntegrator scanIntegrator = IntentIntegrator.forFragment(this);
        scanIntegrator.setOrientation(ActivityInfo.SCREEN_ORIENTATION_SENSOR_PORTRAIT);
        scanIntegrator.setCaptureLayout(R.layout.custom_capture_layout);
        scanIntegrator.setPrompt("");
        scanIntegrator.initiateScan();
And as you see, the scanning area is rectangular. How can i make it square? I also tested it on Nexus 5, and everything was great, the scanner was square and aspect ratio was perfect.

Also, could you give me an advice. I need to set up flashlight along with your scanner, but when I'm trying to connect to camera it drops. Is that possible to use the same camera connection as your library?

**Comment by Chesteer89** [comment] 2015-04-10 10:02
About using torch: I don't know is it possible to run it from Intent right now. I mean default CaptureActivity has build in torch toggle on volume keys.

Imho you'd create your own CaptureActivity and set up:
```
barcodeView.setTorch(true);
```

**Comment by rkistner** [comment] 2015-04-10 10:03
@zavernutiy 

Please try the [3.x branch](https://github.com/journeyapps/zxing-android-embedded/tree/3.x) - the orientation/aspect-ratio issues should be fixed there. Note that you will then have to set the orientation in `AndroidManifest.xml` instead of through `IntentIntegrator` (instructions in the [readme](https://github.com/journeyapps/zxing-android-embedded/blob/3.x/README.md) of the branch).

The flashlight can be managed in one of two ways:

1. Set `cameraSettings.setAutoTorchEnabled(true)`. `AmbientLightManager` will then automatically turn the torch on/off depending on the ambient light.

2. Use `barcodeView.setTorch(true/false);`. This only works if autoToch is not enabled.

Both of the above requires you to create a custom Activity for scanning currently. You can have a look at the [CaptureActivity](https://github.com/journeyapps/zxing-android-embedded/blob/3.x/zxing-android-embedded/src/com/journeyapps/barcodescanner/CaptureActivity.java) to see how it works.

**Comment by zavernutiy** [comment] 2015-04-10 10:23
Thanks, I will try. And let you know if i succeed!

**Comment by zavernutiy** [comment] 2015-04-10 12:15
Thanks a lot! Everything is working perfectly.
