### ISSUE TITLE
AnyOrientation Full screen Scanner

### ISSUE THREAD

**Issue by shiprasinghal1** [journeyapps/zxing-android-embedded#274] opened 2017-02-02 05:34 UTC
#### Description of the problem: 

I want to create fullscreen barcode zxing scanner(not just in middle) in any orientation. How can i achieve that? 

**Which library version are you using?** E.g. 3.2.0. Latest lib version

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**  Phone

**Does the same happen on other devices or an emulator?**

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**

**In the case of an error do you have a stack trace or adb logs?**

**Comment by RanjitPati** [comment] 2017-02-02 05:59
Which issue your are facing ? 

I have implemented this library (zxing-android-embedded)  in my app and also its working for both orientations with full screen. Not faced any issue yet.  

For all devices (14 - latest)

**Comment by shiprasinghal1** [comment] 2017-02-02 06:04
@RanjitPati 
Actually what issue i am facing is: Zxing scanner reading barcode only if its on middle laser. i want scanner to scan barcode in any direction , and from anywhere . Not just middle laser read.

**Comment by RanjitPati** [comment] 2017-02-02 06:11
Not tried yet. But my app is scanning both bar and qr code(full screen). 
Let me customize the library for full screen bar code.

**Comment by shiprasinghal1** [comment] 2017-02-02 06:19
@RanjitPati 
Let me share a link which kind of showing what i am asking for: 
https://drive.google.com/open?id=0B8VAG91bqpKedUZvaVY5T19uV1E 
In this link you will see barcode is getting scan from everywhere not just middle. I hope this will help

**Comment by RanjitPati** [comment] 2017-02-02 09:18
well shipra. they just making the scanning box height to matchparent or something like this and hiding the green line as well..we have to customize the lib a little to do this. let me try once

**Comment by shiprasinghal1** [comment] 2017-02-02 09:48
No not saying that . I able to achieve what u said. Right now my scanning height is match parent and removed the laser in middle  , but issue is: it only scans barcode instance on some product which is holding in portrait mode ? Why it not able to scan barcode showing in any direction(diagonal , horizontal , vertical ). Its only read barcode which is horizontal and in center of scanner...? why? what should i change to achieve it?

**Comment by parvez729** [comment] 2017-02-16 05:52
I implemented zxing library in my project.everything is fine.but when I scan barcode the laser not able to recognize it.in the official barcode scanner app.it's working.

**Comment by Tougee** [comment] 2018-01-03 06:45
@shiprasinghal1 
I'm not sure what u want,  but I try this for full-screen decode
```Kotlin
val p = Point()
windowManager.defaultDisplay.getSize(p)
barcodeView.framingRectSize = Size(p.x, p.y)
```

**Comment by rkistner** [comment] 2019-09-08 08:08
Duplicate of #211.

**Closed by rkistner** 2019-09-08 08:08 UTC
