### ISSUE TITLE
RotationListener Memory Leak

### ISSUE THREAD

**Issue by kbalivetec** [journeyapps/zxing-android-embedded#50] opened 2015-05-20 06:43 UTC
LeakCanary https://github.com/square/leakcanary, indicates a memory leak coming from SystemSensorManager and CameraPreview. Not sure if this is the best solution, but changing  rotationListener = new RotationListener(context) in CameraPreview to rotationListener = new RotationListener(context.getApplicationContext()) fixes the issue.

**Comment by rkistner** [comment] 2015-05-20 06:57
Using `getApplicationContext()` will prevent the Activity from being leaked, but the RotationListener itself could still be leaking. Thanks for reporting, I'll look into this.

**Comment by rkistner** [comment] 2015-05-20 07:21
I'm unable to reproduce the leak. Can you reproduce with the sample application? `rotationListener.disable()` in `CameraPreview#pause()` should already clear the reference, as long as `CameraPreview#pause()` is always called.

**Comment by kbalivetec** [comment] 2015-05-20 07:30
Yes leak occurs in the sample app. rotationListener.disable() gets called but leaks still happens. Here's a dump from logcat.

05-20 17:26:37.619  24255-24270/example.zxing D/dalvikvm﹕ threadid=12 (LeakCanary-Heap-Dump): calling run()
05-20 17:27:07.605  24255-24270/example.zxing I/dalvikvm﹕ hprof: dumping heap strings to "/storage/sdcard0/Download/leakcanary/suspected_leak_heapdump.hprof".
05-20 17:27:17.751  24255-24255/example.zxing D/ActivityThread﹕ SVC-Creating service: CreateServiceData{token=android.os.BinderProxy@41fd30c8 className=com.squareup.leakcanary.DisplayLeakService packageName=example.zxing intent=null}
05-20 17:27:17.753  24255-24763/example.zxing D/dalvikvm﹕ threadid=15 (IntentService[com.squareup.leakcanary.AbstractAnalysisResultService]): calling run()
05-20 17:27:17.757  24255-24255/example.zxing D/ActivityThread﹕ SVC-CREATE_SERVICE handled : 0 / CreateServiceData{token=android.os.BinderProxy@41fd30c8 className=com.squareup.leakcanary.DisplayLeakService packageName=example.zxing intent=null}
05-20 17:27:17.757  24255-24255/example.zxing D/ActivityThread﹕ SVC-Calling onStartCommand: com.squareup.leakcanary.DisplayLeakService@41f379b0, flags=0, startId=1
05-20 17:27:17.758  24255-24255/example.zxing D/ActivityThread﹕ SVC-SERVICE_ARGS handled : 0 / ServiceArgsData{token=android.os.BinderProxy@41fd30c8 startId=1 args=Intent { cmp=example.zxing/com.squareup.leakcanary.DisplayLeakService (has extras) }}
05-20 17:27:17.796  24255-24763/example.zxing D/LeakCanary﹕ In example.zxing:1.0:1.
    * com.journeyapps.barcodescanner.CaptureActivity has leaked:
    * GC ROOT static android.hardware.SystemSensorManager.mAppContextImpl
    * leaks com.journeyapps.barcodescanner.CaptureActivity instance
    * Reference Key: 02e367d0-8abc-420b-9901-20b30da609ba
    * Device: MID MID MID MID
    * Android Version: 4.4.2 API: 19 LeakCanary: 1.3.1
    * Durations: watch=5052ms, gc=139ms, heap dump=494ms, analysis=9784ms
    * Details:
    * Class android.hardware.SystemSensorManager
    |   static $staticOverhead = byte[] [id=0x41c94ec9;length=192;size=208]
    |   static SensorFirstUsed = false
    |   static callerPid = 0
    |   static first_time_stamp = 0
    |   static mAppContextImpl = com.journeyapps.barcodescanner.CaptureActivity [id=0x41fc31c0]
    |   static sFullSensorsList = java.util.ArrayList [id=0x41d0bfb8]
    |   static sHandleToSensor = android.util.SparseArray [id=0x41d0bfd0]
    |   static sSensorModuleInitialized = true
    |   static sSensorModuleLock = java.lang.Object [id=0x41d0d758]
    * Instance of com.journeyapps.barcodescanner.CaptureActivity
    |   barcodeScannerView = com.journeyapps.barcodescanner.CompoundBarcodeView [id=0x41fc6240]
    |   capture = com.journeyapps.barcodescanner.CaptureManager [id=0x41fcdba0]
    |   mActionBar = null
    |   mActivityInfo = android.content.pm.ActivityInfo [id=0x41fc15a8]
    |   mAllLoaderManagers = android.util.ArrayMap [id=0x41fe9858]
    |   mApplication = example.zxing.App [id=0x41f27288]
    |   mWindowManager = android.view.WindowManagerImpl [id=0x41fc3d38]
    |   mWindow = com.android.internal.policy.impl.PhoneWindow [id=0x41fc3670]
    |   mUiThread = java.lang.Thread [id=0x41c39d98]
    |   mTranslucentCallback = null
    |   mComponent = android.content.ComponentName [id=0x41fc1478]
    |   mToken = android.os.BinderProxy [id=0x41fc1548]
    |   mContainer = android.app.Activity$1 [id=0x41fc3338]
    |   mCurrentConfig = android.content.res.Configuration [id=0x41fc35e0]
    |   mDecor = null
    |   mTitle = java.lang.String [id=0x41f3f0c8]
    |   mDefaultKeySsb = null
    |   mSearchManager = null
    |   mResultData = null
    |   mEmbeddedID = null
    |   mParent = null
    |   mMenuInflater = null
    |   mFragments = android.app.FragmentManagerImpl [id=0x41fc32c0]
    |   mHandler = android.os.Handler [id=0x41fc33b8]
    |   mManagedDialogs = null
    |   mInstanceTracker = android.os.StrictMode$InstanceTracker [id=0x41fc3360]
    |   mInstrumentation = android.app.Instrumentation [id=0x41f26000]
    |   mIntent = android.content.Intent [id=0x41fc1370]
    |   mLastNonConfigurationInstances = null
    |   mLoaderManager = null
    |   mManagedCursors = java.util.ArrayList [id=0x41fc3348]
    |   mMainThread = android.app.ActivityThread [id=0x41f1f960]
    |   mLoadersStarted = false
    |   mIdent = 1112718752
    |   mFinished = true
    |   mEnableDefaultActionBarUp = false
    |   mResultCode = 0
    |   mDoReportFullyDrawn = false
    |   mResumed = false
    |   mDestroyed = true
    |   mStartedActivity = false
    |   mStopped = true
    |   mTemporaryPause = false
    |   mDefaultKeyMode = 0
    |   mTitleColor = 0
    |   mTitleReady = true
    |   mConfigChangeFlags = 0
    |   mCheckedForLoaderManager = true
    |   mChangingConfigurations = false
    |   mVisibleFromClient = true
    |   mVisibleFromServer = true
    |   mChangeCanvasToTranslucent = false
    |   mWindowAdded = true
    |   mCalled = true
    |   mBase = android.app.ContextImpl [id=0x41fc33d8]
    |   mInflater = com.android.internal.policy.impl.PhoneLayoutInflater [id=0x41fc3bd0]
    |   mOverrideConfiguration = null
    |   mResources = android.content.res.Resources [id=0x41f251a0]
    |   mTheme = android.content.res.Resources$Theme [id=0x41fc3d50]
    |   mThemeResource = 2131493103
    |   mBase = android.app.ContextImpl [id=0x41fc33d8]

**Comment by rkistner** [comment] 2015-05-20 07:42
Can you reproduce this on an emulator, or alternatively on multiple different devices? Is there any specific sequence of steps to follow to reproduce, or just open and close the CaptureActivity? I'm unable to reproduce it using the sample app on any of my devices so far.

**Comment by kbalivetec** [comment] 2015-05-20 08:06
Your right. I tried running it on another device and it's fine - no leak. Haven't tried an emulator? Seems like some issue specific to a particular device? I have a Tablet, running 4.4.2 and it happens every time, just opening and closing the CaptureActivity, while same app on a Samsung Galaxy S4 running 4.4.2 has no problem.

**Comment by rkistner** [comment] 2015-05-20 08:09
I've managed to reproduce it in an emulator now. It might be a framework bug, in which case I'll just go for the `getApplicationContext()` workaround.

**Comment by rkistner** [comment] 2015-05-20 08:51
I pushed a fix/workaround to the leakcanary branch - will you please test this on your tablet?

**Comment by kbalivetec** [comment] 2015-05-20 11:04
That fixes the issue. BTW. This port of the Zxing library works much better than all the others I've tried. Faster, uses less memory, handles orientation changes, ability to customize, and opening the camera in a background thread. This is the only library that covers everything I need. Thanks!

**Comment by rkistner** [comment] 2015-05-20 11:57
Thanks, great to hear! All those features you mention required quite large rewrite to achieve :)

I'll include the fix in the next release.

**Closed by rkistner** 2015-05-20 11:57 UTC

**Comment by rkistner** [comment] 2015-06-10 08:17
Fix released in v3.0.1.
