### ISSUE TITLE
CameraInstance is not open

### ISSUE THREAD

**Issue by soenkegissel** [journeyapps/zxing-android-embedded#359] opened 2018-01-03 10:04 UTC
#### Description of the problem:

3.5.0
Moto G (5) Plus Android 7.0

**Does the same happen on other devices or an emulator?** Several devices.

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?** No - can't reproduce.

**In the case of an error do you have a stack trace or adb logs?**
com.journeyapps.barcodescanner.camera.CameraInstance.validateOpen (CameraInstance.java:181)
com.journeyapps.barcodescanner.camera.CameraInstance.requestPreview (CameraInstance.java:169)
com.journeyapps.barcodescanner.DecoderThread.requestNextPreview (DecoderThread.java:129)
com.journeyapps.barcodescanner.DecoderThread.decode (DecoderThread.java:173)
com.journeyapps.barcodescanner.DecoderThread.access$000 (DecoderThread.java:22)
com.journeyapps.barcodescanner.DecoderThread$1.handleMessage (DecoderThread.java:38)

![camerainstance](https://user-images.githubusercontent.com/13346316/34516109-bc49808e-f075-11e7-9189-eb4064bbb77d.PNG)

**Comment by benefice-alfa** [comment] 2018-01-16 07:31
Hi, I have the same problem. 
**Description of the problem:**

library version : 3.5.0

**Does the same happen on other devices or an emulator?**
I can not reproduce the crash on my device or emulator, but i got the report from Crashlytics. These are some devices that have the problem

![screen shot 2018-01-16 at 14 24 08](https://user-images.githubusercontent.com/6326715/34976391-072dc058-fac9-11e7-9c58-787204e85782.png)

**Can you reproduce the issue in the sample project included with the library? If not, can you
provide your own sample project or sample code that produces this error?**
I can not reproduce,
this is my code 
```
public void openBarcode() {
        // Add on manifest, then run activity like below
        try {
            IntentIntegrator integrator = IntentIntegrator.forSupportFragment(this);
            integrator.setDesiredBarcodeFormats(IntentIntegrator.ONE_D_CODE_TYPES);
            integrator.setPrompt(compatActivityParent.getString(R.string.hint_scan_barcode));
            integrator.setOrientationLocked(true);
            integrator.initiateScan();
        } catch (IllegalStateException e) {
            showMessage("Camera Error.");
        }

    }
```
i call this method when the user click on option menu of a fragment.

**In the case of an error do you have a stack trace or adb logs?**
```
Fatal Exception: java.lang.IllegalStateException: CameraInstance is not open
       at com.journeyapps.barcodescanner.camera.CameraInstance.validateOpen(CameraInstance.java:181)
       at com.journeyapps.barcodescanner.camera.CameraInstance.requestPreview(CameraInstance.java:169)
       at com.journeyapps.barcodescanner.DecoderThread.requestNextPreview(DecoderThread.java:129)
       at com.journeyapps.barcodescanner.DecoderThread.decode(DecoderThread.java:173)
       at com.journeyapps.barcodescanner.DecoderThread.access$000(DecoderThread.java:22)
       at com.journeyapps.barcodescanner.DecoderThread$1.handleMessage(DecoderThread.java:38)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:148)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

Can you guys tell me what is wrong with my code?

**Comment by uditunpluged** [comment] 2018-02-14 09:14
I had the same problem. I dont have the fix for it right now. When I faced this issue, I thought why not open the existing camera app provided by the manufacturer, when I opened that app, it presented me a dialog that camera is not available and ask me to reboot the device. Now the camera app is working but my app with this library is not.

**Comment by rkistner** [comment] 2019-09-08 08:00
Duplicate of #272.

**Closed by rkistner** 2019-09-08 08:00 UTC
