### ISSUE TITLE
Slow barcode scanning when debugger connected, fine when not

### ISSUE THREAD

**Issue by akiller** [journeyapps/zxing-android-embedded#408] opened 2018-07-02 10:09 UTC
#### Description of the problem:
I'm not sure whether this is an issue with Zxing Embedded or Zxing its-self but I've noticed that if you have the debugger connected whilst trying to read barcodes it appears to take a very long time to process the results. 

E.g., you hover your phone over the barcode, the camera has focused, but it can take several seconds before it decodes the result. Often I've found that I can move the phone away from the barcode and then a few seconds later it finishes processing and shows the result. This seems to imply the processing thread is being slow or being held up. 

If you pulling out the USB cable it appears to start scanning instantly or just as quick as all the other barcode apps would do.

I did once try and fix this myself several months ago and couldn't see anything obvious. Hopefully someone has a better idea.

Is this a known issue?

**Which library version are you using?** E.g. 3.2.0.
The sample app from the latest master branch (aec45c4f10e3769d7449bcb7b82b5d09689512a4)

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**
Various phones and Android builds

**Does the same happen on other devices or an emulator?**
Yes. Unable to test on an emulator though.

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**
Yes, the sample app has this issue.

**In the case of an error do you have a stack trace or adb logs?**
No

**Comment by jossiwolf** [comment] 2018-11-04 09:18
This is driving me crazy. @akiller Have you been able to solve this issue?

**Comment by akiller** [comment] 2018-11-04 10:44
> This is driving me crazy. @akiller Have you been able to solve this issue?

No, sorry . I've not had to do any debugging using ZXing for a while (un)fortunately.

I wonder if it's to do with spamming ADB messages or something and the debugger can't keep up. Might be worth trying to turn them off temporarily.

**Comment by rkistner** [comment] 2018-11-05 07:21
Decoding barcodes is quite a CPU-intensive process. Connecting the debugger disables many optimizations, which could make the code run much slower. So generally it is not unexpected for the scanning to be slower while the debugger is connected.

**Comment by jossiwolf** [comment] 2018-11-09 10:49
> > This is driving me crazy. @akiller Have you been able to solve this issue?
> 
> No, sorry . I've not had to do any debugging using ZXing for a while (un)fortunately.
> 
> I wonder if it's to do with spamming ADB messages or something and the debugger can't keep up. Might be worth trying to turn them off temporarily.
> 
> (p.s., nice bunny 😊)

Alright, thanks! @rkistner's explanation makes sense as well, I guess it's a combination of both.

**Comment by tsuellow** [comment] 2019-08-07 00:37
I have the same issue but for me its just really noticeable on a Samsung device. it even works waaay better on my amazon Fire HD which is the cheapest of the cheap and severely underpowered. I guess you should not rule out that it might be something samsung specific.  let me know if a solution is found.

**Comment by rkistner** [comment] 2019-09-07 19:36
The camera preview resolution can have a big effect on performance, which may explain the difference between the devices.

Closing this issue, since it's expected behaviour.

**Closed by rkistner** 2019-09-07 19:36 UTC
