### ISSUE TITLE
Crash : java.lang.ArithmeticException: divide by zero

### ISSUE THREAD

**Issue by yashasvigirdhar** [journeyapps/zxing-android-embedded#334] opened 2017-10-13 08:02 UTC
#### Description of the problem:

**Which library version are you using?** 3.5.0.

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**

Samsung - Android 7

**Does the same happen on other devices or an emulator?** No

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?** No

**In the case of an error do you have a stack trace or adb logs?**

```
Fatal Exception: java.lang.ArithmeticException: divide by zero
       at com.journeyapps.barcodescanner.CameraPreview.calculateFrames(SourceFile:389)
       at com.journeyapps.barcodescanner.CameraPreview.previewSized(SourceFile:461)
       at com.journeyapps.barcodescanner.CameraPreview.access$300(SourceFile:59)
       at com.journeyapps.barcodescanner.CameraPreview$3.handleMessage(SourceFile:199)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6692)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```

**Comment by noritoshi** [comment] 2017-11-19 10:37
Maybe same problem.
I got the bug report from Crashlytics at Nov 17 2017 18:36 (UTC).
I'm not sure it was caused by the library or a mistake in my code.

**Description of the problem:**

**Which library version are you using?** 3.5.0.

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
Android 5.0)**

Galaxy A8 - Android 6.0.1

**Does the same happen on other devices or an emulator?** No

**Can you reproduce the issue in the sample project included with the library? If not, can you
provide your own sample project or sample code that produces this error?** No

**In the case of an error do you have a stack trace or adb logs?**

Fatal Exception: java.lang.ArithmeticException: divide by zero
       at com.journeyapps.barcodescanner.CameraPreview.calculateFrames(CameraPreview.java:8389)
       at com.journeyapps.barcodescanner.CameraPreview$3.handleMessage(CameraPreview.java:199)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7325)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by alexisv6** [comment] 2018-01-12 19:22
I have the same thing, seems to be all Samsung. I got it on the Galaxy Tab A 8.0/9.7

**Description of the problem:**
**Which library version are you using?** 3.5.0.Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,Android 5.0)Samsung - Android 7Does the same happen on other devices or an emulator? NoCan you reproduce the issue in the sample project included with the library? If not, can youprovide your own sample project or sample code that produces this error? NoIn the case of an error do you have a stack trace or adb logs?Fatal Exception: java.lang.ArithmeticException: divide by zero        at com.journeyapps.barcodescanner.CameraPreview.calculateFrames(SourceFile:389)        at com.journeyapps.barcodescanner.CameraPreview.previewSized(SourceFile:461)        at com.journeyapps.barcodescanner.CameraPreview.access$300(SourceFile:59)        at com.journeyapps.barcodescanner.CameraPreview$3.handleMessage(SourceFile:199)        at android.os.Handler.dispatchMessage(Handler.java:98)        at android.os.Looper.loop(Looper.java:154)        at android.app.ActivityThread.main(ActivityThread.java:6692)        at java.lang.reflect.Method.invoke(Method.java)        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
--

**Comment by alexisv6** [comment] 2018-01-12 19:31
I have the same problem
**Description of the problem:**
**Which library version are you using?** 3.5.0.

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,Android 5.0)** Samsung Galaxy Tab 8.0/9.7 - Android 6/7

**Does the same happen on other devices or an emulator?** No just Samsung so far

**Can you reproduce the issue in the sample project included with the library? If not, can you provide your own sample project or sample code that produces this error?** No

**In the case of an error do you have a stack trace or adb logs?
`Fatal Exception: java.lang.ArithmeticException: divide by zero
       at com.journeyapps.barcodescanner.CameraPreview.calculateFrames(SourceFile:389)
       at com.journeyapps.barcodescanner.CameraPreview.previewSized(SourceFile:461)
       at com.journeyapps.barcodescanner.CameraPreview.access$300(SourceFile:59)
       at com.journeyapps.barcodescanner.CameraPreview$3.handleMessage(SourceFile:199)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6823)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)`

**Comment by nitintechjini** [comment] 2018-05-18 07:38
I am also facing this issue. Any fix for this.

**Comment by kiran-git** [comment] 2018-07-18 06:15
Please let me know if is there any fix for this issue

**Comment by IvanIvanov3** [comment] 2018-07-27 05:01
Hello @rkistner , should we wait for changes?

**Comment by karmil32** [comment] 2018-09-16 18:43
Same problem here. Library version: 3.6.0

`Fatal Exception: java.lang.ArithmeticException
divide by zero
com.journeyapps.barcodescanner.CameraPreview.calculateFrames (SourceFile:385)
com.journeyapps.barcodescanner.CameraPreview.previewSized (SourceFile:469)
com.journeyapps.barcodescanner.CameraPreview.access$300 (SourceFile:60)
com.journeyapps.barcodescanner.CameraPreview$3.handleMessage (SourceFile:200)
android.os.Handler.dispatchMessage (Handler.java:101)
android.os.Looper.loop (Looper.java:164)
android.app.ActivityThread.main (ActivityThread.java:6944)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:327)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1374)`

**Comment by albo1337** [comment] 2018-12-18 22:43
facing the same problem

**Comment by phearme** [comment] 2018-12-21 05:03
+1
Same issue here. Are you accepting pull requests?

**Comment by soenkegissel** [comment] 2018-12-23 21:05
same here.

**Comment by kevag** [comment] 2019-02-15 13:06
We are facing exactly the same bug at random times with Samsung Galaxy S8 Plus(Android version : 8.0.0) and Samsung Galaxy J7 Prime(Android version : 8.1.0) phones. 
Is there any update on this issue?

BRS / Kostas

**Comment by ljfantin** [comment] 2019-02-27 14:27
Any news about this issue ?

**Comment by Cylix** [comment] 2019-05-03 23:06
Any plan to merge these fixes? Is this library still maintained?

**Comment by rkistner** [comment] 2019-09-07 19:03
Should be fixed in v4.0.2.

**Closed by rkistner** 2019-09-07 19:03 UTC

**Comment by FrantisekGazo** [comment] 2021-05-10 09:09
@rkistner can you please add a fix to 3.x version as well?

I'm asking cause our app needs to support android api 21 so we cannot upgrade to 4.x version

**Comment by FrantisekGazo** [comment] 2021-06-11 07:28
Can you please answer? 
If you plan to completely abandon lower android api then 24 could you at least write how you fixed it so maybe I could fork your repo and fix it there at least?

**Comment by rkistner** [comment] 2021-06-11 08:42
The fixes won't be backported.

You can use the latest versions with Android API 14+, either by:
1. Downgrading zxing:core - see https://github.com/journeyapps/zxing-android-embedded#older-sdk-versions
2. OR by using AGP - see https://github.com/journeyapps/zxing-android-embedded/pull/612
