### ISSUE TITLE
The problem with data being empty when using intentIntegrator.setRequestCode()

### ISSUE THREAD

**Issue by VincentYD** [journeyapps/zxing-android-embedded#403] opened 2018-06-06 13:59 UTC
#### Description of the problem:

The following code:

IntentIntegrator.forSupportFragment(fragment)
        .setRequestCode(101)
        .setOrientationLocked(false)
        .initiateScan();
IntentResult scanResult = IntentIntegrator.parseActivityResult(requestCode, resultCode, data)

When I used setRequestCode, I couldn't get any scan results(scanResult is null)
Has anyone found a solution to this problem?

**Comment by ashish-coutloot** [comment] 2018-06-07 10:17
Having same problem

**Comment by rkistner** [comment] 2018-06-07 10:38
Duplicate of https://github.com/journeyapps/zxing-android-embedded/issues/382 - see the fix there.

**Closed by rkistner** 2018-06-07 10:38 UTC
