### ISSUE TITLE
Camera is not released.

### ISSUE THREAD

**Issue by Ponsen** [journeyapps/zxing-android-embedded#69] opened 2015-07-18 17:02 UTC
Hi,

after reaching onActivityResult I have to open the Camera, too. But everytime I'm trying Camera.open() after processing a result, I'm getting an exception: Fail to connect to Camera Service. Without prior scanning it's possible to open the camera.  How can I fix this?

**Comment by rkistner** [comment] 2015-07-20 08:12
I'm guessing the issue is that the camera is closed asynchronously, via CameraInstance/CameraThread (to prevent blocking the UI for camera operations).

There are two options I can think of here:
1. Also use CameraInstance/CameraThread for your camera code. It may not currently support all the functionality you would want, depending on your use case.
2. Wait until CameraThread has released the camera. There isn't currently any API for this, but one could be added. A workaround would be to just wait in a loop/timer until you can access the camera.

**Comment by Ponsen** [comment] 2015-07-20 14:43
Hi,
I ended up doing a fancy animation to suggest some computing^^
Working fine now, thanks.

**Closed** 2015-08-14 08:36 UTC

**Comment by mmelchio** [comment] 2015-12-02 10:16
I got the same Problem. I tried it with:
        Camera c = null;
        boolean cameraAccessible = false;
        while (!cameraAccessible) {
            try {
                c = Camera.open(); // attempt to get a Camera instance
                cameraAccessible = true;
            }
            catch (Exception e){
                Log.v(TAG, "Camera not yet accessible");
            }
        }
        c.release();
It doesn't seem that the camera is available for 5 Seconds. It shouldn't take that long anyways.
Strangely it works fine in 1 out of 10 cases.
