### ISSUE TITLE
Changing to Portrait Mode

### ISSUE THREAD

**Issue by yychun1217** [journeyapps/zxing-android-embedded#15] opened 2014-09-22 03:50 UTC
I tried to change the barcode scanner to portrait mode, yet it does not work for zxing-android-minimal. It only works for zxing-android-legacy. I just don't know why. 
I made changes according to the following site:
http://stackoverflow.com/questions/23403664/zxing-camera-portrait-mode-and-landscape-on-android?rq=1

**Comment by lawloretienne** [comment] 2015-02-19 23:30
This library would be great, but since there is no support for portrait mode then it is useless for me.

**Comment by rkistner** [comment] 2015-02-23 10:40
Duplicate of #16 .

**Closed by rkistner** 2015-02-23 10:40 UTC
